// 이미지 파일 임포트
export { default as ProfileImage } from '/public/assets/image/fubao.jpg'
export { default as DummyHero } from '/public/assets/image/dummy_hero.jpg'

// SVG 파일 임포트
export { default as HomeIcon } from '/public/assets/svg/home-icon.svg'
export { default as ProjectIcon } from '/public/assets/svg/folder-icon.svg'
export { default as PostIcon } from '/public/assets/svg/blog-icon.svg'
export { default as MailIcon } from '/public/assets/svg/mail-icon.svg'
export { default as LocationIcon } from '/public/assets/svg/location-icon.svg'
export { default as ArrowIcon } from '/public/assets/svg/arrow-icon.svg'
export { default as DotsIcon } from '/public/assets/svg/dots-icon.svg'
export { default as DartIcon } from '/public/assets/svg/skills/dart-icon.svg'
export { default as FlutterIcon } from '/public/assets/svg/skills/flutter-icon.svg'
export { default as HTMLIcon } from '/public/assets/svg/skills/html-icon.svg'
export { default as CSSIcon } from '/public/assets/svg/skills/css-icon.svg'
export { default as JavascriptIcon } from '/public/assets/svg/skills/javascript-icon.svg'
export { default as TypescriptIcon } from '/public/assets/svg/skills/typescript-icon.svg'
export { default as ReactIcon } from '/public/assets/svg/skills/react-icon.svg'
export { default as NextIcon } from '/public/assets/svg/skills/next-icon.svg'
export { default as ReduxIcon } from '/public/assets/svg/skills/redux-icon.svg'
export { default as ZustandIcon } from '/public/assets/svg/skills/zustand-icon.svg'
export { default as ReactQueryIcon } from '/public/assets/svg/skills/react-query-icon.svg'
export { default as StyledComponentsIcon } from '/public/assets/svg/skills/styled-components-icon.svg'
export { default as TailwindCSSIcon } from '/public/assets/svg/skills/tailwind-css-icon.svg'
export { default as JavaIcon } from '/public/assets/svg/skills/java-icon.svg'
export { default as SpringBootIcon } from '/public/assets/svg/skills/spring-boot-icon.svg'
export { default as SpringSecurityIcon } from '/public/assets/svg/skills/spring-security-icon.svg'
export { default as INVY } from '/public/assets/svg/INVY.svg'

// Lottie 파일 임포트
export { default as CursorLottie } from '/public/assets/lottie/cursor-lottie.json'
